// Package auth provides authentication and session management for the
// gallery server.
//
// # Architecture overview
//
// Authentication is split into two interfaces:
//
//   - [Authenticator] verifies credentials and returns a [domain.Principal].
//     The concrete implementation is [FileUserStore], which reads a JSON file
//     of bcrypt-hashed users. The interface allows future backends (LDAP,
//     OAuth, etc.) without changing the API layer.
//
//   - [SessionStore] manages opaque session tokens. The concrete
//     implementation is [CookieSessionStore], which stores sessions in an
//     in-memory map keyed by HMAC-signed tokens. Tokens are delivered to
//     clients as HttpOnly, Secure, SameSite=Lax cookies.
//
// # Request flow
//
// On every request, the auth middleware ([api.Server.authMiddleware]) extracts
// the session cookie, calls [SessionStore.Lookup], and if valid, attaches the
// [domain.Principal] to the request context via [WithPrincipal]. Downstream
// handlers retrieve it with [PrincipalFromContext]. A nil principal means the
// request is anonymous.
//
// # CSRF protection
//
// State-changing requests (POST, PATCH, DELETE) must include an X-CSRF-Token
// header. The token is an HMAC-SHA256 of the session token using the server's
// CSRF secret, generated by [GenerateCSRFToken] and validated by
// [ValidateCSRFToken]. The login endpoint is exempt because no session exists
// yet. See csrf.go for the implementation.
//
// # Session storage and scaling
//
// Sessions are stored in a Go map protected by [sync.RWMutex]. This is simple
// and sufficient for single-instance deployments. Limitations:
//
//   - Sessions are lost on server restart (users must re-login).
//   - Horizontal scaling (multiple server instances) is not supported because
//     each instance has its own session map. To support multiple instances,
//     replace [CookieSessionStore] with a shared backend (Redis, PostgreSQL,
//     or signed JWTs).
//   - There is no session expiration or cleanup. Long-running servers will
//     accumulate stale sessions. This is acceptable for small deployments
//     but would need a TTL sweep for high-traffic scenarios.
//
// # User store
//
// [FileUserStore] loads users.json once at startup into an in-memory map.
// It does not watch the file for changes — a server restart is needed to
// pick up user modifications. The [gollery-users] CLI tool manages the
// users.json file format (add/remove users, set passwords, manage groups).
//
// Passwords are stored as bcrypt hashes (cost 10 by default from the CLI).
// Authentication uses [bcrypt.CompareHashAndPassword], which is constant-time
// against the hash to prevent timing attacks.
package auth

import (
	"context"
	"errors"

	"github.com/perrito666/gollery/backend/internal/domain"
)

// ErrInvalidCredentials is returned when login credentials are invalid.
var ErrInvalidCredentials = errors.New("invalid credentials")

// ErrSessionNotFound is returned when a session token does not map to a user.
var ErrSessionNotFound = errors.New("session not found")

// Authenticator verifies user credentials and returns a Principal.
// Implementations may use a local user store, LDAP, OAuth, etc.
type Authenticator interface {
	// Authenticate checks the given credentials and returns a Principal
	// on success. Returns ErrInvalidCredentials on failure.
	Authenticate(ctx context.Context, username, password string) (*domain.Principal, error)
}

// SessionStore manages session tokens.
type SessionStore interface {
	// Create creates a new session for the given principal and returns a token.
	Create(ctx context.Context, p *domain.Principal) (token string, err error)

	// Lookup returns the principal associated with the given token.
	// Returns ErrSessionNotFound if the token is invalid or expired.
	Lookup(ctx context.Context, token string) (*domain.Principal, error)

	// Delete removes a session by token (logout).
	Delete(ctx context.Context, token string) error
}

// principalKey is the context key for storing the current principal.
type principalKey struct{}

// WithPrincipal returns a new context carrying the given principal.
func WithPrincipal(ctx context.Context, p *domain.Principal) context.Context {
	return context.WithValue(ctx, principalKey{}, p)
}

// PrincipalFromContext retrieves the principal from the context.
// Returns nil if no principal is set (anonymous request).
func PrincipalFromContext(ctx context.Context) *domain.Principal {
	p, _ := ctx.Value(principalKey{}).(*domain.Principal)
	return p
}
