#!/usr/bin/env node
/**
 * resolve-theme.js — Build-time override resolution.
 *
 * Scans site/views/ and site/styles/ for overrides.
 * Generates src/_resolved/registry.js with the effective imports.
 * If a site override exists for a view, it wins; otherwise ui-default is used.
 *
 * Usage: node scripts/resolve-theme.js [--print]
 *   --print: print the effective theme map and exit without writing
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, '..', 'src');

const VIEW_NAMES = ['home', 'album', 'asset', 'login', 'not-found', 'forbidden', 'error'];

const printOnly = process.argv.includes('--print');

function resolveViews() {
  const resolved = {};
  for (const name of VIEW_NAMES) {
    const siteView = join(srcDir, 'site', 'views', `${name}.js`);
    if (existsSync(siteView)) {
      resolved[name] = `../site/views/${name}.js`;
    } else {
      resolved[name] = `../ui-default/views/${name}.js`;
    }
  }
  return resolved;
}

function resolveStyles() {
  const styles = ['ui-default/styles/main.css'];
  const siteStylesDir = join(srcDir, 'site', 'styles');
  if (existsSync(siteStylesDir)) {
    for (const f of readdirSync(siteStylesDir)) {
      if (f.endsWith('.css')) {
        styles.push(`site/styles/${f}`);
      }
    }
  }
  return styles;
}

function loadSiteConfig() {
  const configPath = join(srcDir, 'site', 'site.config.json');
  if (existsSync(configPath)) {
    return JSON.parse(readFileSync(configPath, 'utf-8'));
  }
  return { siteName: 'Gallery', theme: 'default' };
}

const views = resolveViews();
const styles = resolveStyles();
const siteConfig = loadSiteConfig();

if (printOnly) {
  console.log('Effective theme resolution:');
  console.log('');
  console.log('Views:');
  for (const [name, path] of Object.entries(views)) {
    const source = path.includes('/site/') ? 'site' : 'ui-default';
    console.log(`  ${name.padEnd(15)} -> ${source}`);
  }
  console.log('');
  console.log('Styles:');
  for (const s of styles) {
    console.log(`  ${s}`);
  }
  console.log('');
  console.log('Site config:');
  console.log(`  siteName: ${siteConfig.siteName}`);
  console.log(`  theme:    ${siteConfig.theme}`);
  process.exit(0);
}

// Generate _resolved/registry.js
const outDir = join(srcDir, '_resolved');
mkdirSync(outDir, { recursive: true });

let code = '/* Auto-generated by resolve-theme.js — do not edit */\n\n';

// Import views
for (const [name, path] of Object.entries(views)) {
  const safeName = name.replace(/-/g, '_');
  code += `import * as ${safeName}View from '${path}';\n`;
}

code += '\n';

// Export site config
code += `export const siteConfig = ${JSON.stringify(siteConfig, null, 2)};\n\n`;

// Export resolved style paths (for reference, CSS is handled separately)
code += `export const stylesheets = ${JSON.stringify(styles)};\n\n`;

// Export a function that registers all views into a registry
code += `export function registerAll(registry) {\n`;
for (const name of VIEW_NAMES) {
  const safeName = name.replace(/-/g, '_');
  code += `  registry.register('${name}', ${safeName}View);\n`;
}
code += '}\n';

writeFileSync(join(outDir, 'registry.js'), code);
console.log('resolve-theme: wrote src/_resolved/registry.js');
